### ISSUE TITLE
User types and how to handle them

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#10]
• admin - all access
• candidate - can post content specific to their campaign only
• voter - can access all public-facing content, must register to take part in reader polling
• sponsor ? - maybe this is for uploading their logo and text of a question, and maybe to receive reporting on how many answers they've gotten or views or something like that.

**Comment by mzagaja** [comment]
Are the candidate accounts going to need to do anything other than answer the survey and upload a photo and video? 

Videos might have some of their own issues since they're so large and varied in formats. The path of least resistance might be to have them upload to their own YouTube accounts and then send to us, but that prevents you from having control (i.e. if they randomly decide to take it down in the future) and monetization potential. But it might require additional resources/work to intake the uploads.

**Comment by doughardy-ctnj** [comment]
That should be it for candidate accounts - answer the survey, edit their personal info, upload photo and video. We should get a notification any time they edit though, to be safe. If that's doable.

I agree - youtube or vimeo or embed for video would be smart. FB video embed/upload?
