### ISSUE TITLE
E-Mail Text for Candidates

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#31]
I need the e-mail text that we're going to send candidates to invite them to take the survey. We also need to decide when we're going to do the launch for the candidate e-mail blast. I'm going to have to make a script to auto-build the user accounts for each candidate and then send the e-mail to them inviting them to the survey. I might be able to do it Wed and/or Thursday night if I don't hit any snags.

**Comment by doughardy-ctnj** [comment]
Lawyer suggested that I make sure our invite says CTNewsJunkie reserves the right to remove any posts it deems inappropriate, but I will have something for you asap.

In terms of how we're going about this - the invite only aspect is required, right? We couldn't just send them a note from mailchimp?

Or maybe I'll send them a note from mailchimp warning them that it's coming and to watch for it, maybe watch for a specific email address & subject line?

**Comment by mzagaja** [comment]
Yeah the invite only aspect for candidates to is the security measure and also a user experience upgrade. If I generate accounts for each candidate and send them a link so they can login and take them to the survey in one shot it would probably improve our response rates and MailChimp cannot generate those. Though maybe we could generate them in a CSV and then ship them to MailChimp that way. Right now it is set to come from your e-mail address but I can use a different one.

**Comment by doughardy-ctnj** [comment]
I'm nervous about the login process. I'm still being denied continually when I try to log in. Did you delete that candidate account we'd set up for me to use for testing?

**Comment by mzagaja** [comment]
I am 100% confident in the login process at this point, but logging in is very challenging for most people (and I say that earnestly, I've tried to get rooms of people to sign in to the App Store and it fails amazingly often). That being said I think your issue might just be that when I was testing your issues with the login I changed your password so I could hijack your account and verify it was an issue on our end and not an issue on your end. After fixing the issues I sent you an e-mail with a new password, but if you missed it that is probably why it is not working.

**Comment by doughardy-ctnj** [comment]
ah thats right
technology

**Comment by doughardy-ctnj** [comment]
i was able to log in

we need to reorder the questions - which file is that in?

**Comment by mzagaja** [comment]
https://github.com/mzagaja/ctnewsjunkie_voterguide/blob/master/app/views/candidates/_form.html.erb for data entry from the candidate and https://github.com/mzagaja/ctnewsjunkie_voterguide/blob/master/app/views/candidates/_candidate.html.erb is display to the users. Both must be edited. It is ok to change only the question text without touching the stuff around it (i.e. the "<%= candidate.q3 %>") because the question numbers in the database are not yet locked down to a specific question.

**Comment by doughardy-ctnj** [comment]
got it - edited both

can i move the order of the questions around?

**Comment by doughardy-ctnj** [comment]
can I just change the candidate.q1 to candidate.q5 and so on?

**Comment by doughardy-ctnj** [comment]
Here's the text of the email:

SUBJECT:
You're invited to fill out our candidate questionnaire!

Hello and welcome to CTNewsJunkie's latest addition - Vote.CTNewsJunkie.com - a Voter Guide and Candidate Questionnaire.

We're writing to you because you are listed as the contact person for your campaign, and we're inviting you to fill out our questionnaire asap, so that we can share it with voters before the election. 

Vote.CTNewsJunkie.com is here as a service to candidates who need to get their message out, and to voters who need to learn more about candidates in order to make an informed decision.

It's got a lot of bells and whistles, so to speak. We've included an option for voters to check their voter registrations, find out who their candidates are locally using geolocation, locate their polling place, and also to start the process of registering to vote and/or vote absentee.

But the goal here is to get as much participation as possible from all the candidates, and then to push their answers out to as many readers as possible. Help us out by sharing your District pages on your social networks!

We're launching this site pretty late in the election season and hope to iron out as many bugs as possible so that we can make spectacular use of it in the next election. Let us know if you're having any problems on the site.

Thanks in advance,

Any questions or problems, contact us Xxxxxx.
-Christine Stuart

P.S. CTNewsJunkie reserves the right to remove any inappropriate or defamatory responses to questions on the site.

**Comment by doughardy-ctnj** [comment]
OK - yeah we have some @ctnewsjunkie.com addresses we can choose from for
the mail response



*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=15da025e-7e09-4707-99ae-e796f8270d9e>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
Yep just copy and paste the text from one spot to the other question spot

**Comment by mzagaja** [comment]
No that won't do anything. Only changing the order of the questions in the
view will.

**Comment by doughardy-ctnj** [comment]
ok - i'll look at it in a bit. wrestling the news bear at the moment.
